# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Escriba en menos de 240carácteres la descripción del producto.', max_length=240)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
