# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Escriba en menos de 240 car\xe1cteres la descripci\xf3n del producto.', max_length=240, verbose_name='Descripci\xf3n: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad: '),
        ),
    ]
