# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.BinaryField(blank=True),
        ),
    ]
