# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
    ]
