# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180331_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_user',
            field=models.CharField(default=1, max_length=10, verbose_name='Id_Usuario '),
            preserve_default=False,
        ),
    ]
